# Generated by Django 3.2.3 on 2021-05-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
